spring.graphql.graphiql.enabled=true
spring.graphql.schema.introspection.enabled=true
org.neo4j.migrations.transaction-mode=PER_STATEMENT

spring.graphql.cors.allowed-origins=http://localhost:3000

okta.oauth2.issuer=https://dev-4uc47y6c2weqzcjc.jp.auth0.com/
okta.oauth2.client-id=hjtaovJaEqp6bRQVgk87jMl1sUk0GXZh
okta.oauth2.audience=${okta.oauth2.issuer}api/v2/

# GraphQL Ã¬Â¶ÂÃªÂ°Â Ã¬ÂÂ¤Ã¬Â Â
spring.graphql.path=/graphql
spring.graphql.websocket.path=/graphql
spring.graphql.schema.printer.enabled=true
spring.graphql.schema.locations=classpath:graphql/
spring.graphql.schema.file-extensions=.graphqls,.gql

spring.datasource.url=jdbc:mysql://localhost:3306/aurasphere
spring.datasource.username=elice-user
spring.datasource.password=qwer1234!@
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# GraphQL Ã¬Â¿Â¼Ã«Â¦Â¬ Ã«Â³ÂµÃ¬ÂÂ¡Ã«ÂÂ Ã¬Â ÂÃ­ÂÂ Ã¬ÂÂ¤Ã¬Â Â
spring.graphql.schema.max-depth=10
spring.graphql.schema.max-query-complexity=100